/**
 * PLANETS_DATA
 * Centralized data source for the Planetary Age Calculator project.
 * Uses verified astronomical colors (NASA / USGS planetary mapping).
 * No radioactive neon gradients.
 */
const PLANETS_DATA = {
    sun: {
        name: 'Sun',
        symbol: '☉',
        type: 'Star',
        diameter: '1,392,700 km',
        mass: '1.989 × 10³⁰ kg',
        period: 0.0,
        color: '#f59e0b',
        accentGlow: 'rgba(245, 158, 11, 0.15)',
        temperature: '5,778 K (surface)',
        composition: 'Hydrogen (73%), Helium (25%)',
        funFact: 'The Sun contains 99.86% of the mass in the Solar System',
        nasaUrl: 'https://solarsystem.nasa.gov/solar-system/sun/overview/'
    },
    mercury: {
        name: 'Mercury',
        symbol: '☿',
        type: 'Terrestrial Planet',
        diameter: '4,879 km',
        mass: '3.301 × 10²³ kg',
        period: 0.241,
        color: '#a8b2c1',
        accentGlow: 'rgba(168, 178, 193, 0.15)',
        distance: '57.9 million km',
        orbitalPeriod: '88 Earth days',
        dayLength: '59 Earth days',
        temperature: '-173°C to 427°C',
        composition: 'Iron core, silicate mantle',
        funFact: 'Mercury has no atmosphere and extreme temperature variations',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/mercury/overview/'
    },
    venus: {
        name: 'Venus',
        symbol: '♀',
        type: 'Terrestrial Planet',
        diameter: '12,104 km',
        mass: '4.867 × 10²⁴ kg',
        period: 0.615,
        color: '#e2be82',
        accentGlow: 'rgba(226, 190, 130, 0.15)',
        distance: '108.2 million km',
        orbitalPeriod: '225 Earth days',
        dayLength: '243 Earth days',
        temperature: '462°C (hottest planet)',
        composition: 'Dense CO₂ atmosphere, sulfuric acid clouds',
        funFact: 'Venus rotates backwards and is the hottest planet in our solar system',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/venus/overview/'
    },
    earth: {
        name: 'Earth',
        symbol: '♁',
        type: 'Terrestrial Planet',
        diameter: '12,756 km',
        mass: '5.972 × 10²⁴ kg',
        period: 1.0,
        color: '#5d8aa8',
        accentGlow: 'rgba(93, 138, 168, 0.15)',
        distance: '149.6 million km',
        orbitalPeriod: '365.25 days',
        dayLength: '24 hours',
        temperature: '-89°C to 58°C',
        composition: 'Nitrogen (78%), Oxygen (21%) atmosphere',
        funFact: 'The only known planet with life and liquid water on its surface',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/earth/overview/'
    },
    mars: {
        name: 'Mars',
        symbol: '♂',
        type: 'Terrestrial Planet',
        diameter: '6,792 km',
        mass: '6.39 × 10²³ kg',
        period: 1.881,
        color: '#c25736',
        accentGlow: 'rgba(194, 87, 54, 0.15)',
        distance: '227.9 million km',
        orbitalPeriod: '687 Earth days',
        dayLength: '24.6 hours',
        temperature: '-87°C to -5°C',
        composition: 'Thin CO₂ atmosphere, iron oxide surface',
        funFact: 'Mars has the largest volcano in the solar system - Olympus Mons',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/mars/overview/'
    },
    jupiter: {
        name: 'Jupiter',
        symbol: '♃',
        type: 'Gas Giant',
        diameter: '142,984 km',
        mass: '1.898 × 10²⁷ kg',
        period: 11.862,
        color: '#c99564',
        accentGlow: 'rgba(201, 149, 100, 0.15)',
        distance: '778.6 million km',
        orbitalPeriod: '12 Earth years',
        dayLength: '9.9 hours',
        temperature: '-108°C',
        composition: 'Hydrogen (89%), Helium (10%)',
        funFact: 'Jupiter has over 80 moons and a Great Red Spot storm larger than Earth',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/jupiter/overview/'
    },
    saturn: {
        name: 'Saturn',
        symbol: '♄',
        type: 'Gas Giant',
        diameter: '120,536 km',
        mass: '5.683 × 10²⁶ kg',
        period: 29.456,
        color: '#d8c29d',
        accentGlow: 'rgba(216, 194, 157, 0.15)',
        distance: '1.432 billion km',
        orbitalPeriod: '29.5 Earth years',
        dayLength: '10.7 hours',
        temperature: '-139°C',
        composition: 'Hydrogen (96%), Helium (3%)',
        funFact: 'Saturn has spectacular rings made of ice and rock particles',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/saturn/overview/'
    },
    uranus: {
        name: 'Uranus',
        symbol: '♅',
        type: 'Ice Giant',
        diameter: '51,118 km',
        mass: '8.681 × 10²⁵ kg',
        period: 84.07,
        color: '#93b8be',
        accentGlow: 'rgba(147, 184, 190, 0.15)',
        distance: '2.867 billion km',
        orbitalPeriod: '84 Earth years',
        dayLength: '17.2 hours',
        temperature: '-197°C',
        composition: 'Water, methane, ammonia ices',
        funFact: 'Uranus rotates on its side at a 98-degree angle',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/uranus/overview/'
    },
    neptune: {
        name: 'Neptune',
        symbol: '♆',
        type: 'Ice Giant',
        diameter: '49,528 km',
        mass: '1.024 × 10²⁶ kg',
        period: 164.81,
        color: '#4b70dd',
        accentGlow: 'rgba(75, 112, 221, 0.15)',
        distance: '4.515 billion km',
        orbitalPeriod: '165 Earth years',
        dayLength: '16.1 hours',
        temperature: '-201°C',
        composition: 'Water, methane, ammonia ices',
        funFact: 'Neptune has the fastest winds in the solar system, up to 2,100 km/h',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/neptune/overview/'
    },
    pluto: {
        name: 'Pluto',
        symbol: '♇',
        type: 'Dwarf Planet',
        diameter: '2,376 km',
        mass: '1.303 × 10²² kg',
        period: 248.1,
        color: '#998d83',
        accentGlow: 'rgba(153, 141, 131, 0.15)',
        distance: '5.906 billion km',
        orbitalPeriod: '248 Earth years',
        dayLength: '153.3 hours',
        temperature: '-228°C to -238°C',
        composition: 'Nitrogen, methane, carbon monoxide ices',
        funFact: 'Pluto has a giant heart-shaped glacier made of nitrogen ice named Tombaugh Regio',
        nasaUrl: 'https://solarsystem.nasa.gov/planets/pluto/overview/'
    }
};
